### PR TITLE
docs: Add README.md file

### PR DESCRIPTION
**Pull request by Awambeng**
This commit adds the README.md file to provide detailed documentation and instructions for the project. The README.md file contains information about the project's description, features, installation steps, usage instructions, and license information. It aims to help users understand the project and effectively utilize its functionalities.

### CODE REVIEW

**Review by stephane-segning — CHANGES_REQUESTED** [review]
Please document well the usage of the script. This script is missing some part of it

**Comment by Awambeng** [comment]
@stephane-segning all is well implemented you can check on https://github.com/ADORSYS-GIS/gis-random-groups/pull/2/commits/98a1e5f0755d8ce4b824d0259138aef898ea9e32

**Review by stephane-segning — APPROVED** [review]
Nice work

**Comment by Awambeng** [comment]
> Nice work

Thanks prof

**Pull request merged**
